/**
 * Codex Provider Installer — Codex-Specific Installation Logic
 * ==============================================================
 * REQ-0115: Codex Installation and Doctor Paths
 *
 * Implements install/update/uninstall/doctor for the Codex provider.
 * Simpler than the Claude installer: no hooks, no settings.json merge,
 * no symlinks. Uses the same fs-helpers imports.
 *
 * API signature parity with Claude installer (FR-005).
 *
 * @module src/providers/codex/installer
 */

import { join } from 'node:path';
import { createHash } from 'node:crypto';
import {
  existsSync, mkdirSync, writeFileSync, readFileSync,
  readdirSync, rmSync, statSync
} from 'node:fs';

import { getCodexConfig, getProjectionPaths } from './projection.js';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Compute SHA-256 hash of a string.
 * @param {string} content
 * @returns {string}
 */
function contentHash(content) {
  return createHash('sha256').update(content, 'utf-8').digest('hex');
}

/**
 * Generate default content for a projection path file.
 * @param {string} key - Projection path key
 * @returns {string} Generated content
 */
function generateContent(key) {
  switch (key) {
    case 'instructions':
      return '# Codex Agents\n\nGenerated by iSDLC Codex provider adapter.\n\nThis file contains agent instructions for Codex tasks.\n';
    case 'teamSpec':
      return '# Team Specification\n\nGenerated by iSDLC Codex provider adapter.\n\nTeam structure and roles for the current project.\n';
    case 'contentModel':
      return '# Content Model\n\nGenerated by iSDLC Codex provider adapter.\n\nContent classification and section mappings.\n';
    case 'skillManifest':
      return '# Skills\n\nGenerated by iSDLC Codex provider adapter.\n\nSkill definitions and injection bindings.\n';
    default:
      return '';
  }
}

/**
 * Read the config.json metadata (content hashes for generated files).
 * @param {string} configPath
 * @returns {Object}
 */
function readConfigMeta(configPath) {
  try {
    if (existsSync(configPath)) {
      return JSON.parse(readFileSync(configPath, 'utf-8'));
    }
  } catch {
    // Fall through
  }
  return {};
}

/**
 * Write the config.json with metadata.
 * @param {string} configPath
 * @param {Object} config
 */
function writeConfigMeta(configPath, config) {
  writeFileSync(configPath, JSON.stringify(config, null, 2), 'utf-8');
}

/**
 * Remove a directory if it is empty.
 * @param {string} dirPath
 */
function removeIfEmpty(dirPath) {
  try {
    if (existsSync(dirPath) && statSync(dirPath).isDirectory()) {
      const entries = readdirSync(dirPath);
      if (entries.length === 0) {
        rmSync(dirPath, { recursive: true });
      }
    }
  } catch {
    // Non-fatal
  }
}

// ---------------------------------------------------------------------------
// installCodex
// ---------------------------------------------------------------------------

/**
 * Install Codex-specific framework files into a project.
 *
 * Creates .codex/ with instruction files and provider config.
 *
 * @param {string} projectRoot - Target project directory
 * @param {Object} [options={}] - Installation options
 * @returns {Promise<{ success: boolean, filesCreated: string[], errors: string[] }>}
 */
export async function installCodex(projectRoot, options = {}) {
  const filesCreated = [];
  const errors = [];

  try {
    const config = getCodexConfig();
    const paths = getProjectionPaths();
    const codexDir = join(projectRoot, config.frameworkDir);
    const configPath = join(projectRoot, paths.providerConfig);

    // 1. Create .codex/ directory
    if (!existsSync(codexDir)) {
      mkdirSync(codexDir, { recursive: true });
    }

    // 2. Generate content hashes for tracking
    const fileHashes = {};

    // 3. Generate instruction files
    for (const [key, relativePath] of Object.entries(paths)) {
      if (key === 'providerConfig') continue; // config.json handled separately

      const fullPath = join(projectRoot, relativePath);
      const content = generateContent(key);

      if (content) {
        writeFileSync(fullPath, content, 'utf-8');
        fileHashes[relativePath] = contentHash(content);
        filesCreated.push(relativePath);
      }
    }

    // 4. Write config.json with provider info and content hashes
    const configData = {
      provider: 'codex',
      frameworkVersion: '0.1.0-alpha',
      generatedAt: new Date().toISOString(),
      fileHashes
    };
    writeConfigMeta(configPath, configData);
    filesCreated.push(paths.providerConfig);

  } catch (err) {
    errors.push(err.message);
  }

  return {
    success: errors.length === 0,
    filesCreated,
    errors
  };
}

// ---------------------------------------------------------------------------
// updateCodex
// ---------------------------------------------------------------------------

/**
 * Update Codex instruction files from latest core models.
 * Preserves user-modified content (detects edits via content hash comparison).
 *
 * @param {string} projectRoot - Target project directory
 * @param {Object} [options={}] - Update options
 * @returns {Promise<{ success: boolean, filesUpdated: string[], filesSkipped: string[], errors: string[] }>}
 */
export async function updateCodex(projectRoot, options = {}) {
  const filesUpdated = [];
  const filesSkipped = [];
  const errors = [];

  try {
    const paths = getProjectionPaths();
    const configPath = join(projectRoot, paths.providerConfig);
    const config = readConfigMeta(configPath);
    const oldHashes = config.fileHashes || {};
    const newHashes = { ...oldHashes };

    for (const [key, relativePath] of Object.entries(paths)) {
      if (key === 'providerConfig') continue;

      const fullPath = join(projectRoot, relativePath);
      const newContent = generateContent(key);
      if (!newContent) continue;

      // Check if user modified the file
      if (existsSync(fullPath)) {
        const currentContent = readFileSync(fullPath, 'utf-8');
        const currentHash = contentHash(currentContent);
        const storedHash = oldHashes[relativePath];

        if (storedHash && currentHash !== storedHash) {
          // User modified — skip
          filesSkipped.push(relativePath);
          continue;
        }
      }

      // Regenerate
      writeFileSync(fullPath, newContent, 'utf-8');
      newHashes[relativePath] = contentHash(newContent);
      filesUpdated.push(relativePath);
    }

    // Update config.json
    writeConfigMeta(configPath, {
      ...config,
      fileHashes: newHashes,
      updatedAt: new Date().toISOString()
    });

  } catch (err) {
    errors.push(err.message);
  }

  return {
    success: errors.length === 0,
    filesUpdated,
    filesSkipped,
    errors
  };
}

// ---------------------------------------------------------------------------
// uninstallCodex
// ---------------------------------------------------------------------------

/**
 * Remove Codex-specific generated files.
 * Preserves user-modified content.
 *
 * @param {string} projectRoot - Target project directory
 * @param {Object} [options={}] - Uninstall options
 * @returns {Promise<{ success: boolean, filesRemoved: string[], filesPreserved: string[], errors: string[] }>}
 */
export async function uninstallCodex(projectRoot, options = {}) {
  const filesRemoved = [];
  const filesPreserved = [];
  const errors = [];

  try {
    const config_obj = getCodexConfig();
    const paths = getProjectionPaths();
    const configPath = join(projectRoot, paths.providerConfig);
    const config = readConfigMeta(configPath);
    const storedHashes = config.fileHashes || {};
    const codexDir = join(projectRoot, config_obj.frameworkDir);

    for (const [key, relativePath] of Object.entries(paths)) {
      if (key === 'providerConfig') continue; // Remove config last

      const fullPath = join(projectRoot, relativePath);
      if (!existsSync(fullPath)) continue;

      const currentContent = readFileSync(fullPath, 'utf-8');
      const currentHash = contentHash(currentContent);
      const storedHash = storedHashes[relativePath];

      if (storedHash && currentHash !== storedHash) {
        // User modified — preserve
        filesPreserved.push(relativePath);
      } else {
        // Unmodified or no hash — remove
        rmSync(fullPath);
        filesRemoved.push(relativePath);
      }
    }

    // Remove config.json
    if (existsSync(configPath)) {
      rmSync(configPath);
      filesRemoved.push(paths.providerConfig);
    }

    // Remove .codex/ if empty
    removeIfEmpty(codexDir);

  } catch (err) {
    errors.push(err.message);
  }

  return {
    success: errors.length === 0,
    filesRemoved,
    filesPreserved,
    errors
  };
}

// ---------------------------------------------------------------------------
// doctorCodex
// ---------------------------------------------------------------------------

/**
 * Validate Codex installation health.
 *
 * @param {string} projectRoot - Project directory
 * @returns {Promise<{ healthy: boolean, checks: Array<{ name: string, passed: boolean, message: string }> }>}
 */
export async function doctorCodex(projectRoot) {
  const checks = [];

  const config = getCodexConfig();
  const paths = getProjectionPaths();
  const codexDir = join(projectRoot, config.frameworkDir);

  // Check 1: .codex/ directory exists
  const dirExists = existsSync(codexDir);
  checks.push({
    name: 'codex-directory-exists',
    passed: dirExists,
    message: dirExists ? '.codex/ directory exists' : '.codex/ directory missing'
  });

  if (!dirExists) {
    return { healthy: false, checks };
  }

  // Check 2: config.json present and valid
  const configPath = join(projectRoot, paths.providerConfig);
  let configValid = false;
  if (existsSync(configPath)) {
    try {
      const parsed = JSON.parse(readFileSync(configPath, 'utf-8'));
      configValid = parsed.provider === 'codex';
    } catch {
      configValid = false;
    }
  }
  checks.push({
    name: 'config-json-valid',
    passed: configValid,
    message: configValid ? 'config.json is valid' : 'config.json missing or invalid'
  });

  // Check 3: Instruction files exist
  let allFilesPresent = true;
  for (const [key, relativePath] of Object.entries(paths)) {
    if (key === 'providerConfig') continue;
    const fullPath = join(projectRoot, relativePath);
    const fileExists = existsSync(fullPath);
    if (!fileExists) {
      allFilesPresent = false;
    }
    checks.push({
      name: `file-${key}`,
      passed: fileExists,
      message: fileExists ? `${relativePath} exists` : `${relativePath} missing`
    });
  }

  const healthy = checks.every(c => c.passed);
  return { healthy, checks };
}
