#!/bin/bash

# iSDLC Framework - Status Report Generator
# Generates a markdown report of project status

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Check if in a project directory
if [ ! -f ".isdlc/state.json" ]; then
    echo -e "${RED}Error: Not in an iSDLC project directory${NC}"
    exit 1
fi

# Check for jq
if ! command -v jq &> /dev/null; then
    echo -e "${RED}Error: jq is required for report generation${NC}"
    echo "Install with: brew install jq (macOS) or apt install jq (Linux)"
    exit 1
fi

STATE_FILE=".isdlc/state.json"
REPORT_FILE="${1:-.isdlc/status-report.md}"
TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

# Extract information
PROJECT_NAME=$(jq -r '.project.name' "$STATE_FILE")
PROJECT_DESC=$(jq -r '.project.description // "No description"' "$STATE_FILE")
PROJECT_CREATED=$(jq -r '.project.created' "$STATE_FILE")
FRAMEWORK_VERSION=$(jq -r '.framework_version' "$STATE_FILE")
CURRENT_PHASE=$(jq -r '.current_phase' "$STATE_FILE")

# Generate report
cat > "$REPORT_FILE" << EOF
# iSDLC Status Report

**Project**: $PROJECT_NAME
**Generated**: $TIMESTAMP
**Framework Version**: $FRAMEWORK_VERSION

---

## Project Overview

- **Name**: $PROJECT_NAME
- **Description**: $PROJECT_DESC
- **Created**: $PROJECT_CREATED
- **Current Phase**: $CURRENT_PHASE

---

## Phase Status

| Phase | Name | Status | Started | Completed | Artifacts |
|-------|------|--------|---------|-----------|-----------|
EOF

# Add phase rows
PHASES=(
    "01-requirements:Requirements Capture"
    "02-architecture:Architecture & Blueprint"
    "03-design:Design & API Contracts"
    "04-test-strategy:Test Strategy & Design"
    "05-implementation:Implementation"
    "06-testing:Integration & Testing"
    "07-code-review:Code Review & QA"
    "08-validation:Independent Validation"
    "09-cicd:Version Control & CI/CD"
    "10-local-testing:Local Development & Testing"
    "11-test-deploy:Test Environment Deployment"
    "12-production:Production Deployment"
    "13-operations:Production Operations"
)

for phase_info in "${PHASES[@]}"; do
    PHASE_ID="${phase_info%%:*}"
    PHASE_NAME="${phase_info#*:}"

    STATUS=$(jq -r ".phases[\"$PHASE_ID\"].status // \"unknown\"" "$STATE_FILE")
    STARTED=$(jq -r ".phases[\"$PHASE_ID\"].started // \"-\"" "$STATE_FILE")
    COMPLETED=$(jq -r ".phases[\"$PHASE_ID\"].completed // \"-\"" "$STATE_FILE")
    ARTIFACT_COUNT=$(jq -r ".phases[\"$PHASE_ID\"].artifacts | length" "$STATE_FILE")

    # Format status with emoji
    case $STATUS in
        "completed") STATUS_DISPLAY="✅ Completed" ;;
        "in_progress") STATUS_DISPLAY="🔄 In Progress" ;;
        "pending") STATUS_DISPLAY="⏳ Pending" ;;
        *) STATUS_DISPLAY="❓ $STATUS" ;;
    esac

    # Format dates
    if [ "$STARTED" != "-" ] && [ "$STARTED" != "null" ]; then
        STARTED=$(echo "$STARTED" | cut -d'T' -f1)
    else
        STARTED="-"
    fi

    if [ "$COMPLETED" != "-" ] && [ "$COMPLETED" != "null" ]; then
        COMPLETED=$(echo "$COMPLETED" | cut -d'T' -f1)
    else
        COMPLETED="-"
    fi

    # Highlight current phase
    if [ "$PHASE_ID" == "$CURRENT_PHASE" ]; then
        echo "| **$PHASE_ID** | **$PHASE_NAME** | **$STATUS_DISPLAY** | $STARTED | $COMPLETED | $ARTIFACT_COUNT |" >> "$REPORT_FILE"
    else
        echo "| $PHASE_ID | $PHASE_NAME | $STATUS_DISPLAY | $STARTED | $COMPLETED | $ARTIFACT_COUNT |" >> "$REPORT_FILE"
    fi
done

# Add blockers section
cat >> "$REPORT_FILE" << EOF

---

## Blockers

EOF

BLOCKER_COUNT=$(jq '.blockers | length' "$STATE_FILE")
if [ "$BLOCKER_COUNT" -eq 0 ]; then
    echo "No active blockers." >> "$REPORT_FILE"
else
    echo "| ID | Phase | Description | Status | Created |" >> "$REPORT_FILE"
    echo "|----|----- |-------------|--------|---------|" >> "$REPORT_FILE"

    jq -r '.blockers[] | "| \(.id) | \(.phase) | \(.description) | \(.status) | \(.created | split("T")[0]) |"' "$STATE_FILE" >> "$REPORT_FILE"
fi

# Add artifacts section
cat >> "$REPORT_FILE" << EOF

---

## Artifacts by Phase

EOF

for phase_info in "${PHASES[@]}"; do
    PHASE_ID="${phase_info%%:*}"
    PHASE_NAME="${phase_info#*:}"

    ARTIFACTS=$(jq -r ".phases[\"$PHASE_ID\"].artifacts[]? // empty" "$STATE_FILE")

    if [ -n "$ARTIFACTS" ]; then
        echo "### $PHASE_ID: $PHASE_NAME" >> "$REPORT_FILE"
        echo "" >> "$REPORT_FILE"
        echo "$ARTIFACTS" | while read -r artifact; do
            echo "- \`$artifact\`" >> "$REPORT_FILE"
        done
        echo "" >> "$REPORT_FILE"
    fi
done

# Add history section (last 10 entries)
cat >> "$REPORT_FILE" << EOF

---

## Recent History

| Timestamp | Agent | Action |
|-----------|-------|--------|
EOF

jq -r '.history | sort_by(.timestamp) | reverse | .[0:10][] | "| \(.timestamp | split("T") | .[0] + " " + (.[1] | split(".")[0])) | \(.agent) | \(.action) |"' "$STATE_FILE" >> "$REPORT_FILE"

# Add footer
cat >> "$REPORT_FILE" << EOF

---

*Report generated by iSDLC Framework v$FRAMEWORK_VERSION*
EOF

echo -e "${GREEN}Report generated: $REPORT_FILE${NC}"
